build:
  binary: lightproxy
  gcflags:
    - -trimpath={{.Env.GOPATH}}
  asmflags:
    - -trimpath={{.Env.GOPATH}}"
  goos:
    - darwin
    - linux
  goarch:
    - amd64

archives:
  - format: tar.gz
    files:
      - LICENSE

release:
  github:
    owner: octavore
    name: lightproxy
